services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-sube
    restart: always
    ports:
      - "${PORT_NGINX:-80}:80"
      # - "8443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/${NGINX_CONF_FILE:-default.conf}:/etc/nginx/conf.d/default.conf
      # - ./docker/nginx/certs:/etc/nginx/certs  # Monta la carpeta de certificados
      # - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php
      - redis
    networks:
      - appnetwork

  redis:
    image: redis:latest
    container_name: redis-sube
    restart: always
    ports:
      - "${PORT_REDIS:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-sube
    restart: always
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9002:9000"
    networks:
      - appnetwork
    depends_on:
      redis:
        condition: service_healthy
  
volumes:
  redis_data:

networks:
  appnetwork:
    external: true