networks:
  appnetwork:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-sube
    restart: always
    ports:
      - "${PORT_NGINX:-80}:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/${NGINX_CONF_FILE:-default.conf}:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/certs:/etc/nginx/certs  # Monta la carpeta de certificados
      # - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php
      - redis
    networks:
      - appnetwork

  mysql:
    image: mysql:8.2
    container_name: mysql-sube
    restart: always
    tty: true
    ports:
      - "${PORT_MYSQL:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/sube.sql:/docker-entrypoint-initdb.d/sube.sql
    networks:
      - appnetwork
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-sube
    environment:
      PMA_HOST: mysql-sube
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PORT_PHPMYADMIN:-81}:80"      
    networks:
      - appnetwork
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis-sube
    restart: always
    ports:
      # - "6379:6379"
      - "${PORT_REDIS:-6379}:6379"      
    volumes:
      - redis_data:/data
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-sube
    restart: always
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env
    ports:
      - "${PORT_PHP_MAPPING:-9000}:9000"      
    networks:
      - appnetwork
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  
volumes:
  mysql_data:
  redis_data: